package handlers

import (
	_ "places_api/docs" // This will be generated by swag

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// SetupRoutes configures all the routes for the new API design
func (h *Handler) SetupRoutes(router *gin.Engine) {
	// Health check endpoint
	router.GET("/healthcheck", h.HandleHealthcheck)

	// Swagger documentation endpoint
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Public API v1
	v1 := router.Group("api/v1")
	{
		// Areas endpoints
		areas := v1.Group("/areas")
		{
			areas.GET("/resolve", h.HandleResolveArea)
			areas.GET("/children", h.HandleGetAreaChildren)
		}

		// Places endpoints
		places := v1.Group("/places")
		{
			places.GET("/top", h.HandleGetTopPlaces)
			places.GET("/near", h.HandleGetNearbyPlaces)
			places.GET("/search", h.HandleSearchPlaces)
			places.GET("/:id", h.HandleGetPlaceDetails)
		}

		// AI endpoints
		ai := v1.Group("/ai")
		{
			ai.POST("/plan", h.HandleGeneratePlan)
			ai.POST("/chat", h.HandleTravelChat)
		}

		// Admin endpoints (protect these with auth in production)
		admin := v1.Group("/admin")
		{
			adminAreas := admin.Group("/areas")
			{
				adminAreas.POST("/bootstrap", h.HandleBootstrapArea)
				adminAreas.GET("/status", h.HandleGetAreaStatus)
			}
		}
	}
}
