package handlers

import (
	_ "places_api/docs" // This will be generated by swag
	"places_api/internal/middlewares"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// SetupRoutes configures all the routes for the new API design
func (h *Handler) SetupRoutes(router *gin.Engine) {
	// Add logging middleware
	router.Use(middlewares.Logging())

	// Health check endpoint
	router.GET("/healthcheck", h.HandleHealthcheck)

	// Swagger documentation endpoint
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Public API v1
	v1 := router.Group("v1")
	{
		// Areas endpoints
		areas := v1.Group("/areas")
		{
			areas.GET("/resolve", h.HandleResolveArea)
		}

		// Places endpoints
		places := v1.Group("/places")
		{
			places.GET("/top", h.HandleGetTopPlaces)
			places.GET("/search", h.HandleSearchPlaceByTextQuery)
		}

		// Jobs endpoints
		jobs := v1.Group("/jobs")
		{
			jobs.GET("/:jobId/status", h.HandleJobStatus)
		}

		// Airports endpoints
		airports := v1.Group("/airports")
		{
			airports.POST("/major-city", h.HandleDetermineAirportMajorCity)
		}
	}
}
