// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthcheck": {
            "get": {
                "description": "Get the health status of the Places API service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "Service is healthy",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/admin/areas/bootstrap": {
            "post": {
                "description": "Queue background refresh/warm for an area's place cache",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Bootstrap area cache",
                "parameters": [
                    {
                        "description": "Bootstrap request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.BootstrapRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Bootstrap queued successfully",
                        "schema": {
                            "$ref": "#/definitions/types.BootstrapResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/admin/areas/status": {
            "get": {
                "description": "Get refresh status and cache statistics for an area",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get area cache status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Area key to check status for",
                        "name": "area",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Area status information",
                        "schema": {
                            "$ref": "#/definitions/types.AreaStatus"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/areas/children": {
            "get": {
                "description": "Get child areas for hierarchical navigation (e.g., cities in a country)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "areas"
                ],
                "summary": "List child areas",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Area key of parent area",
                        "name": "parent",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated child types to return",
                        "name": "types",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of results to return (default: 20, max: 50)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination (default: 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Children response",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/areas/resolve": {
            "get": {
                "description": "Turn free-text queries like \"Rome, Italy\" into canonical area keys with geometry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "areas"
                ],
                "summary": "Resolve area from text query",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Free-text location query",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Return multiple candidates instead of best match",
                        "name": "multi",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Queue background refresh for default categories",
                        "name": "bootstrap",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Multiple area results when multi=true",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Area"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/places/near": {
            "get": {
                "description": "Fast radial search using PostGIS over cached places",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "places"
                ],
                "summary": "Find nearby places",
                "parameters": [
                    {
                        "type": "number",
                        "description": "Latitude of center point",
                        "name": "lat",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Longitude of center point",
                        "name": "lon",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Search radius in meters (default: 1200, max: 5000)",
                        "name": "radius",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated categories to filter",
                        "name": "cats",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of results (default: 40, max: 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Language preference",
                        "name": "lang",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Nearby places response",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/places/search": {
            "get": {
                "description": "Typeahead search over cached place names within a given area",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "places"
                ],
                "summary": "Search places by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Area key to search within",
                        "name": "area",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Search query text (prefix/fuzzy)",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated categories to filter",
                        "name": "cats",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of results (default: 20, max: 50)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Language preference",
                        "name": "lang",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Search results",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/places/top": {
            "get": {
                "description": "Return ranked places for an area from cache",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "places"
                ],
                "summary": "Get top places for area",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Canonical area key",
                        "name": "area",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated categories (attraction,restaurant,cafe,bar,hotel)",
                        "name": "cats",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of results (default: 50, max: 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination (default: 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Language preference",
                        "name": "lang",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Group results by category",
                        "name": "group_by",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Top places response",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        },
                        "headers": {
                            "X-Cache": {
                                "type": "string",
                                "description": "Cache hit/miss status"
                            },
                            "X-Refresh-Queued": {
                                "type": "string",
                                "description": "Whether refresh was queued"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/places/{id}": {
            "get": {
                "description": "Get detailed information for a specific place",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "places"
                ],
                "summary": "Get place details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Place ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Place details",
                        "schema": {
                            "$ref": "#/definitions/types.PlaceDetail"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Place not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "types.Area": {
            "type": "object",
            "properties": {
                "admin_level": {
                    "type": "integer"
                },
                "area_key": {
                    "type": "string"
                },
                "bbox": {
                    "$ref": "#/definitions/types.BoundingBox"
                },
                "center": {
                    "$ref": "#/definitions/types.Coordinate"
                },
                "country_code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "refresh_queued": {
                    "type": "boolean"
                },
                "refreshed_at": {
                    "type": "string"
                },
                "type": {
                    "description": "country|region|city|locality|neighborhood",
                    "type": "string"
                }
            }
        },
        "types.AreaStatus": {
            "type": "object",
            "properties": {
                "area_key": {
                    "type": "string"
                },
                "last_job": {
                    "$ref": "#/definitions/types.JobStatus"
                },
                "last_refresh_at": {
                    "type": "string"
                },
                "places_count": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "stale": {
                    "type": "boolean"
                }
            }
        },
        "types.BootstrapRequest": {
            "type": "object",
            "required": [
                "area_key"
            ],
            "properties": {
                "area_key": {
                    "type": "string"
                },
                "cats": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "force": {
                    "type": "boolean"
                }
            }
        },
        "types.BootstrapResponse": {
            "type": "object",
            "properties": {
                "area_key": {
                    "type": "string"
                },
                "job_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "types.BoundingBox": {
            "type": "object",
            "properties": {
                "east_lon": {
                    "type": "number"
                },
                "north_lat": {
                    "type": "number"
                },
                "south_lat": {
                    "type": "number"
                },
                "west_lon": {
                    "type": "number"
                }
            }
        },
        "types.Coordinate": {
            "type": "object",
            "properties": {
                "lat": {
                    "type": "number"
                },
                "lon": {
                    "type": "number"
                }
            }
        },
        "types.JobStatus": {
            "type": "object",
            "properties": {
                "duration_ms": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "types.PlaceDetail": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "area_key": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lat": {
                    "type": "number"
                },
                "lon": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "popularity": {
                    "type": "number"
                },
                "sources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Source"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "types.Source": {
            "type": "object",
            "properties": {
                "source": {
                    "type": "string"
                },
                "source_id": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Places API",
	Description:      "A cache-first Places API for location search and discovery",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
