// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthcheck": {
            "get": {
                "description": "Get the health status of the Places API service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "Service is healthy",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/areas/resolve": {
            "get": {
                "description": "Turn free-text queries like \"Rome, Lazio, Italy\" into canonical area keys with geometry.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "areas"
                ],
                "summary": "Resolve area from text query",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Free-text location query",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Return multiple candidates instead of best match",
                        "name": "multi",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Queue background refresh for default categories",
                        "name": "bootstrap",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Multiple area results when multi=true",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Area"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/places/top": {
            "get": {
                "description": "Return ranked places for an area from cache",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "places"
                ],
                "summary": "Get top places for area",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Canonical area key",
                        "name": "area",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated categories (attraction,restaurant,cafe,bar,hotel)",
                        "name": "cats",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of results (default: 50, max: 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination (default: 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Language preference",
                        "name": "lang",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Group results by category",
                        "name": "group_by",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Top places response",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        },
                        "headers": {
                            "X-Cache": {
                                "type": "string",
                                "description": "Cache hit/miss status"
                            },
                            "X-Refresh-Queued": {
                                "type": "string",
                                "description": "Whether refresh was queued"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "types.Area": {
            "type": "object",
            "properties": {
                "admin_level": {
                    "type": "integer"
                },
                "area_key": {
                    "type": "string"
                },
                "bbox": {
                    "$ref": "#/definitions/types.BoundingBox"
                },
                "center": {
                    "$ref": "#/definitions/types.Coordinate"
                },
                "country_code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "refresh_queued": {
                    "type": "boolean"
                },
                "refreshed_at": {
                    "type": "string"
                },
                "type": {
                    "description": "country|region|city|locality|neighborhood",
                    "type": "string"
                }
            }
        },
        "types.BoundingBox": {
            "type": "object",
            "properties": {
                "east_lon": {
                    "type": "number"
                },
                "north_lat": {
                    "type": "number"
                },
                "south_lat": {
                    "type": "number"
                },
                "west_lon": {
                    "type": "number"
                }
            }
        },
        "types.Coordinate": {
            "type": "object",
            "properties": {
                "lat": {
                    "type": "number"
                },
                "lon": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Places API",
	Description:      "A cache-first Places API for location search and discovery",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
